version: "3.4"
services:

  linkshelf:
    image: linkshelf:latest
    build:
      context: .
      target: dev
    container_name: linkshelf
    volumes:
      - .:/opt/app
    ports:
      - "8080:8080"
    command: bash -c "echo Making migrations && manage.py makemigrations && manage.py migrate && echo Running server
      &&  manage.py runserver 0.0.0.0:8080"
